
[tool.semantic_release]
# Can be removed or set to true once we are v1
major_on_zero = false
tag_format = "v{version}"
tag_format = "{version}"

[tool.semantic_release.publish]
upload_to_vcs_release = false

[tool.semantic_release.changelog]
template_dir = ".semantic_release"

[tool.semantic_release.changelog.environment]
trim_blocks = true
lstrip_blocks = true

[tool.semantic_release.branches.release]
match = "(mainline|release)"
